### ISSUE TITLE
Changelog or history

### ISSUE THREAD

**Issue by AlexWayfer** [ovity/octotree#1003]
I saw a notification that Octotree extension in my browser was updated from 5.x version to 6.0. It look like major update and I'm interested in what there are new.

I see you had `HISTORY` file: #710. But now I don't see anything like this neither in the repository nor on the site.

**Comment by buunguyen** [comment]
We now move the changes directly into the extension. When you upgrade, you should see a yellow badge at the top of the tree to view change details. If you don't see it, please uninstall and re-install.

**Comment by AlexWayfer** [comment]
> When you upgrade, you should see a yellow badge at the top of the tree to view change details.

It was disabled at upgrade.

I've enabled and saw nothing.

> If you don't see it, please uninstall and re-install.

Done, but still nothing. I don't see any yellow badge and on LMB click nothing happens. Please, reopen. I think, you can add a Changelog somewhere on the site and fetch it into extension, if you want. Or compile it from repository on build step.

**Comment by buunguyen** [comment]
That's strange. Anyway, here's the summary. 

* Support GitHub authentication
* Cleaner UI that blends with GitHub
* Improved search with highlighting and short key support
* Much faster performance, up to 3x on large repositories
* [Pro] Many enhancements to pull request review and bug fixes
* [Pro] 12 more dark themes
* [Pro] Automatically apply light and dark theme based on OS preference
* [Pro] 3 additional file icon themes
* [Pro] 1 more code font

**Comment by AlexWayfer** [comment]
> Anyway, here's the summary.

OK, thanks, but it's a resolution of specific case, not common. But… as you want.

**Comment by buunguyen** [comment]
Got it. Still don't know what the new feature badge doesn't show up. But that's our resolution.
