### ISSUE TITLE
Octotree keep disappearing after click

### ISSUE THREAD

**Issue by julzheng** [ovity/octotree#1133]
### Description
Initially it started okay, but when you explore and click on each individual file, the sidebar then go missing.

### Environment (if bug)

* Octotree version: 7.5.1
* Browser & version: Chrome Version 103.0.5060.53 (Official Build) (64-bit)
* OS & version: Ubuntu 20.04.4 LTS
* Screenshot, if any (drag an image here)

https://user-images.githubusercontent.com/1755417/175478080-137d2625-53f9-4ca3-98ed-7709589720ef.mp4

* Console error log below this line

Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/ovity/octotree:163 Refused to load the font 'https://github.com/fonts/fontawesome.woff2' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/ovity/octotree:163 Refused to load the font 'https://github.com/fonts/mfixx.woff2' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/ovity/octotree:163 Refused to load the font 'https://github.com/fonts/devopicons.woff2' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/ovity/octotree:163 Refused to load the font 'https://github.com/fonts/file-icons.woff2' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

/ovity/octotree:163 Refused to load the font 'https://github.com/fonts/octicons.woff2' because it violates the following Content Security Policy directive: "font-src github.githubassets.com".

**Comment by jdreesen** [comment]
I have the same issue in Firefox.

### Environment

* Octotree version: v7.5.1
* Browser & version: 101.0.1 (64-Bit)
* OS & version: Ubuntu 20.04.4 LTS

**Comment by d1y** [comment]
same issues, And i use Chrome 103.0.5060.53

**Comment by wfern** [comment]
Same issue in Microsoft Edge

Edge: 103.0.1264.37
Octotree: v7.5.1

As said in the original post when it is a full reload it appears normally but in any type of navigation within Github it disappears.

**Comment by jesusmah** [comment]
same issue here on Chrome Version 103.0.5060.53 (Official Build) (x86_64)

**Comment by basarYargici** [comment]
Same isssue in Opera.

<b> Environment<b>
* Octotree version: v7.5.0
* Browser & version: 87.0.4390.45 
* OS & version: Windows 10 64-bit

**Comment by danhgit** [comment]
Thank you all for reporting. GitHub has been changing the way they load their pages, causing this issue. We're figuring out how to fix this.

**Comment by pwm** [comment]
Times like this when I realise how much I rely on this amazing tool.

**Comment by DamianArado** [comment]
Same  : ( 
All the best Dan!

**Comment by danhgit** [comment]
We've just released v7.5.2 that fixes the issue (hope no further changes from GitHub 😅). It should already be available for Firefox. Chrome usually takes about a day while Edge, Opera and Safari usually take longer. The code change is quite tricky, please let us know if you experiment any issue. Thank you.

**Comment by jm-janzen** [comment]
Might be a coincidence, but I had to remove and re-download Octotree before it started working again, even when Settings view showed Octotree v7.5.2.

Thanks for the incredibly quick turnaround! I was just at the point of exasperation when I discovered this thread. :pray: 

- Firefox 101.0.1
- Octotree v7.5.2

**Comment by andres-lowrie** [comment]
In case anyone else was wondering how to update on chrome. 

Right Click the Extension > Manage Extension

Then on the top right you should see "Developer Mode" in the top right, click that and then click on the "Update" button that will appear

**Comment by kwbr** [comment]
Still experiencing the issue.

- Firefox 102.0
- Octotree 7.5.2

**Comment by danhgit** [comment]
The cause was GitHub changed page loading approach again after we had implemented the fix. We've just released another hot fix 7.5.3. Please look out for that version.

**Comment by jdreesen** [comment]
Seems to work for me again on Firefox with 7.5.3 :)

**Comment by s-bose** [comment]
Having the same problem with Edge. 
Version: 103.0.1264.37
OS: Pop OS 22.04

**Comment by jdreesen** [comment]
@s-bose with Octotree v7.5.3?

**Comment by danhgit** [comment]
@s-bose sadly, Edge is very slow when coming to approving releases. Might take up to a week. You should consider install the Chrome extension to Edge instead.

**Comment by s-bose** [comment]
> @s-bose with Octotree v7.5.3?

No the Edge version is currently 7.5.1

**Comment by s-bose** [comment]
> @s-bose sadly, Edge is very slow when coming to approving releases. Might take up to a week. You should consider install the Chrome extension to Edge instead.

This fixed it. Thank you!
