### ISSUE TITLE
Github thinks user is not logged in

### ISSUE THREAD

**Issue by benwaffle** [ovity/octotree#567]
### Description
When switching between files using octotree, GitHub has this annoying banner even though I'm logged in.

### Environment (if bug)

* Octotree version: 2.5.1
* Browser & version: Firefox 63.0.1
* OS & version: Arch Linux, Latest
* Screenshot, if any (drag an image here): 
![image](https://user-images.githubusercontent.com/1713819/47946843-c04ec700-dee7-11e8-8f25-a530305d5648.png)
* Console error log below this line: no errors

**Comment by buunguyen** [comment]
This doesn't explain why this is an Octotree problem.

**Comment by benwaffle** [comment]
When I disable octotree, this issue does not occur. This only happens when switching between files using octotree

**Comment by nphi1212** [comment]
It's weird. I can't reproduce the bug

**Comment by duylam** [comment]
@benwaffle 

I can't reproduce the bug, my env

- Octotree version: 2.5.1
- Browser & version: Firefox 63.0
- OS & version: Mac OS 10.13.4

Is there any special thing on your environment: do you have any Personal Token saved currently ? Does the "Join Github today" banner appear on other tabs e.g. Project, Insight, etc. ? Does it still appear when clicking on Dismiss ?

**Comment by benwaffle** [comment]
- i have a personal token
- no, only on files when switched-to using octotree
- dismiss is actually a broken link (the page returns 404)
- this problem doesn't seem to be happening on my mac

**Comment by duylam** [comment]
Thanks @benwaffle 

> this problem doesn't seem to be happening on my mac

Me neither, because I don't have the Arch Linux available on my machine so I can't give help here. Appreciate if somebody would give a helping hand for debugging

**Comment by mauforonda** [comment]
I have this issue in Firefox 63, Ubuntu 16.04.

Pjax requests launched from `pjax.js` in Firefox, both Linux and Windows, lack pjax headers (`x-pjax` and `x-pjax-container`) and url attribute (`_pjax`). I reproduced this in Firefox 63 and 65, Linux, and Firefox 63, Windows. Somehow, it works as expected in Windows, but not Linux. Chrome 70 doesn't do this in both Linux and Windows. 

Pjax only seems to be an issue when used from an extension. Both the [pjax demo server](https://pjax.herokuapp.com/) and making pjax requests directly in Github through the browser console work fine. Maybe it has to do with how content script XHR requests are implemented in Firefox for Linux.

**Comment by mdarse** [comment]
Can reproduce the same issue with Firefox 66 on macOS 10.12.6.

**Comment by mauforonda** [comment]
For anyone else facing this issue, I fixed it by resetting `Content Blocking` settings back to `Standard` in Firefox. Still no idea what was the problem, but now the tree works fine!

**Comment by maricn** [comment]
Experiencing this on `Firefox 67.0b6 (64-bit)` on macOS `10.14.3 (18D109)`. Tried disabling octotree and then everything works fine. But it happens not only when i use octotree to navigate, but also when i move between tabs and projects. It shows up on any page.

I will try @mauforonda's fix with disabling content blocking, but only to confirm the behavior. I don't want to change my content blocking settings because of octotree.

**Comment by buunguyen** [comment]
I don't have Arch Linux to test or reproduce this. If someone can send over a PR, that'd be great.

**Comment by maricn** [comment]
@buunguyen just if you missed it - this reportedly happens on Ubuntu and osx as well.

**Comment by buunguyen** [comment]
Can anyone try the v3 branch? (I tried, couldn't reproduce OSX/Firefox 66. Don't have Firefox 67.)

**Comment by ovsyankin** [comment]
this is still reproduced in 3.0.8, Firefox 67.0 under Windows

**Comment by mdarse** [comment]
Can reproduce on macOS 10.13.6, Firefox 71.0a1 & Octotree 3.0.8.

**Comment by buunguyen** [comment]
It's been a while and there have been many changes in both GH and Octotree. If this still happens, please let me know and I'll re-open. Thanks.
