### ISSUE TITLE
Some pages are infinitely loading

### ISSUE THREAD

**Issue by ammmze** [ovity/octotree#987]
### Description
There appears to be an issue with the plugin when loading some pages on GitHub. Primarily on pages where you are viewing an image, such as [this](https://github.com/ovity/octotree/blob/master/icons/icon128.png) one. You'll see a little loading progress bar at the top of the page continuously pop up over and over as well as the browser page loading notification at the bottom of the page. It appears that turning off the multitab feature stops the infinite loading.

### Environment (if bug)

* Octotree version: 5.2.1
* Browser & version: Chrome  83.0.4103.116
* OS & version: macOS 10.15.3
* Screenshot, if any (drag an image here)
![octotree-inifite-loading](https://user-images.githubusercontent.com/203336/87730385-76217e00-c77c-11ea-9510-8a1228d78db7.gif)

* Console error log below this line ... no console errors

**Comment by marianogenovese** [comment]
I have this same behaviour in private repos and public repos.

**Comment by zackproser** [comment]
Same behavior here - disabling the plugin immediately resolves the issue.

**Comment by ChrisDuggin** [comment]
Here is a public repo you can use to replicate. 
https://github.com/facebook/prop-types/blob/master/README.md

**Comment by debuggy** [comment]
Same bug happened today in chrome, however in firefox the extension works fine.

**Comment by IShinji** [comment]
I have the same behavior.

**Comment by kiyanwang** [comment]
I have the same behavior in chrome. I've had to disable the extension.

**Comment by buunguyen** [comment]
We released a hot fix (5.4.0). Should be available soon in all supported browsers.

**Comment by ammmze** [comment]
Thank you @buunguyen! Looks good to me 👍

**Comment by buunguyen** [comment]
Just an update for people who see this thread, the new release is already available in Chrome, Firefox and Safari. It's not yet available in Opera though. For some reason, Opera has been very slow in approving since last month. Once it's available, I'll update and close this thread.

**Comment by rosarch** [comment]
I have the latest hotfix (5.4.0) and can still see the issue.

MAC - Version 10.15.5
Chrome - Version 84.0.4147.89 (Official Build) (64-bit)

I see it on a Github Enterprise site that I have added under site access.

**Comment by buunguyen** [comment]
@rosarch does your GHE have the new or old GitHub UI?

**Comment by rosarch** [comment]
Yeah, guess that is going to be a problem :-(

**Comment by buunguyen** [comment]
@rosarch I'm sorry, can you confirm that your GitHub Enterprise has the new or old GitHub design? A redacted screenshot would be great. Feel free to email it to support@octotree.io if you can't share it here.

**Comment by rosarch** [comment]
My bad, I should have added more detail on my reply, I can confirm it is using the old UI

<img width="1013" alt="Screenshot 2020-07-19 at 19 03 54" src="https://user-images.githubusercontent.com/1331548/87881681-c4d84d80-c9f2-11ea-905f-8122e5c3fd0c.png">

**Comment by buunguyen** [comment]
Thanks, appreciated the details. We're looking into this.

**Comment by buunguyen** [comment]
@rosarch I forgot to ask, did the previous version (before 5.4) worked fine or also have the same issue?

**Comment by rosarch** [comment]
I am not 100% sure, I use GitHub quite a lot and only noticed the issue yesterday, I then found this thread, went to see what version I was on and noted I was already on 5.4 then added my post here.

**Comment by buunguyen** [comment]
Thanks. Once we have a fix, would you mind helping us test it before we release to the store? If you don't mind, please send an email to support@octotree.io so that we can send you the binary (when it's available).

**Comment by sqybi** [comment]
I'm an enterprise user and I also encountered this issue on our GHE, along with several colleagues. Our GHE has an old UI design. This issue really blocks us and I'd also like to help to test once you have a fix.

**Comment by buunguyen** [comment]
@sqybi great, there are different versions of GHE, so more help is great. Please email support@octotree.io. We're working on a fix now and will send the binary you and @rosarch soon.

**Comment by buunguyen** [comment]
Just a follow up for Opera users: Opera has just approved version 5.4.0.

**Comment by Vimal-N** [comment]
@buunguyen I'm using the 5.4.0 version of the extension in chrome 83.0.4103.106 build. I'm still having the infinitely loading page issue as of 07/21 10 am EST. I'm using the Extension on GitHub Enterprise Server 2.20.11.

**Comment by buunguyen** [comment]
Thanks for reporting. We just released a hot fix (5.4.1) for this issue on GitHub Enterprise. Should be available shortly.

**Comment by Vimal-N** [comment]
> Thanks for reporting. We just released a hot fix (5.4.1) for this issue on GitHub Enterprise. Should be available shortly.

Thanks! with the latest version 5.4.1 I don't experience the infinity loading issue.
